version: '3.9'

volumes:

  prometheus-data:
    driver: local

  grafana-data:
    driver: local

  redis-data:
    driver: local

services:

  # Reverse proxy
  traefik:
    image: traefik:v2.9
    container_name: ${PROJECT}-reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"

  # VTN server for HPT
  vtn-hpt:
    build:
      context: vtn-hpt
    image: vtn-hpt
    container_name: ${PROJECT}-vtn-hpt
    hostname: vtn-hpt
    ports:
      - 5000:5000 # for aiomonitor
      - 8000:8000 # for prometheus client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vtnhpt.rule=Host(`${HOST}`) && PathPrefix(`/Test-HPT-AIT`)"
      - "traefik.http.routers.vtnhpt.entrypoints=web"
      - "traefik.http.services.vtnhpt.loadbalancer.server.port=8081"
      - "traefik.http.routers.vtnhpt.middlewares=vtnhptreplaceprefix"
      - "traefik.http.middlewares.vtnhptreplaceprefix.replacepathregex.regex=^/Test-HPT-AIT/(.*)"
      - "traefik.http.middlewares.vtnhptreplaceprefix.replacepathregex.replacement=/$$1"
    # profiles:
    #   - all
    #   - hpt

  # VTN server for TRIALOG
  vtn-trialog:
    build:
      context: vtn-trialog
    image: vtn-trialog
    container_name: ${PROJECT}-vtn-trialog
    hostname: vtn-trialog
    depends_on: [redis]
    ports:
      - 5001:5001 # for aiomonitor
      - 8001:8001 # for prometheus client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vtntrialog.rule=Host(`${HOST}`) && PathPrefix(`/Test-TRIALOG-AIT`)"
      - "traefik.http.routers.vtntrialog.entrypoints=web"
      - "traefik.http.services.vtn.loadbalancer.server.port=8082"
      - "traefik.http.routers.vtntrialog.middlewares=vtntrialogreplaceprefix"
      - "traefik.http.middlewares.vtntrialogreplaceprefix.replacepathregex.regex=^/Test-TRIALOG-AIT/(.*)"
      - "traefik.http.middlewares.vtntrialogreplaceprefix.replacepathregex.replacement=/$$1"
    # profiles:
    #   - all
    #   - trialog

  # Retrieve flex forecast from TRIALOG
  flex-trialog:
    build:
      context: flex-trialog
    image: flex-trialog
    container_name: ${PROJECT}-flex-trialog
    hostname: flex-trialog
    ports:
      - 8002:8002 # for prometheus client
    # profiles:
    #   - all
    #   - trialog

  # Time series database
  prometheus:
    image: prom/prometheus
    container_name: ${PROJECT}-prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/config/prometheus.yml"
    # profiles:
    #   - all

  # Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: ${PROJECT}-grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/data-sources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    restart: unless-stopped
    # profiles:
    #   - all

  # Database
  redis:
    image: redis:6.2-alpine
    container_name: ${PROJECT}-redis
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes: 
      - redis-data:/data

  # Simple service for checking the connection.
  whoami:
    image: "traefik/whoami"
    container_name: ${PROJECT}-whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
